[package]
name = "jobworkerp-client"
version = "0.1.0"
authors = ["sutr-app"]
edition = "2021"

[dependencies]
anyhow = "1"
prost = "0.12"
prost-types = "0.12"
tonic = { version = "0.10" }
tokio = { version = "1", features = ["full"] }

[build-dependencies]
tonic-build = { version = "0.10", features = ["prost"] }
