[package]
name = "jobworkerp-client"
version = "0.5.1"
authors = ["sutr-app"]
edition = "2021"

[dependencies]
anyhow = "1"
prost = "0.13"
prost-types = "0.13"
tonic = { version = "0.12" }
tokio = { version = "1", features = ["full"] }

[build-dependencies]
tonic-build = { version = "0.12", features = ["prost"] }
